[keybindings.Explorer]
"<q>" = "Quit"  # Quit the application
"<Ctrl-d>" = "Quit"  # Another way to quit
"<Ctrl-c>" = "Quit"  # Yet another way to quit
"<Ctrl-z>" = "Suspend"  # Suspend the application
"<2>" = { SwitchTo = "TodoList" }
"<3>" = { SwitchTo = "Inspector" }
[keybindings.TodoList]
"<q>" = "Quit"  # Quit the application
"<Ctrl-d>" = "Quit"  # Another way to quit
"<Ctrl-c>" = "Quit"  # Yet another way to quit
"<Ctrl-z>" = "Suspend"  # Suspend the application
"<1>" = { SwitchTo = "Explorer" }
"<3>" = { SwitchTo = "Inspector" }
[keybindings.Inspector]
"<q>" = "Quit"  # Quit the application
"<Ctrl-d>" = "Quit"  # Another way to quit
"<Ctrl-c>" = "Quit"  # Yet another way to quit
"<Ctrl-z>" = "Suspend"  # Suspend the application
"<1>" = { SwitchTo = "Explorer" }
"<2>" = { SwitchTo = "TodoList" }
