[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls-aws-lc-rs" ,"sqlite", "macros", "migrate", "chrono"] }
thiserror = "2.0.12"
directories = "6.0.0"
nanoid = "0.4.0"
