[package]
name = "tars-cli"
version = "0.1.0"
edition = "2024"


[dependencies]
common = {path = "../common"}
clap = { version = "4.5.34", features = ["derive"] }
color-eyre = "0.6.3"
log = "0.4.27"
tokio = { version = "1.44.1", features = ["full"] }
